name: wallpix
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  http: ^0.13.4
  mix: ^0.0.5
  rive: ^0.8.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgIcons/
    - assets/animations/
